#pragma once

/*
 NAME					FLAG(1B)									DATA(VAR)																	CHECKSUM(4B)
LOG_IN:					  0			LEN_NAME(1)			NAME(V)					LEN_PSWD(1)			PSWD(XOR)(V)						
LOG_IN_RP:				  1			IS_LOG_IN(1)		USER_TYPE(1)			LEVEL(4)			XP(8)				PASSED(4)
LOG_IN_RC:				  2			IS_LOG_IN(1)		UID(4)					USER_TYPE(1)			LEVEL(4)			WORD_CON(4)			
SIGN_UP:				  3			LEN_NAME(1)			NAME(V)					LEN_PSWD(1)			PSWD(V)
SIGN_UP_R:				  4			IS_SIGN_UP(1)		UID(4)
MY_INFO:				  5			UID(4)
MY_INFO_R:				  6			LEVEL(4)			XP(8)					PASSED(4)
														WORD_CON(4)
CHANGE_ROLE:			  7			UID(4)
CHANGE_ROLE_R:			  8			NULL(0)
USER_LIST:				  9			USER_TYPE(1)		USER_PER_PAGE(2)		PAGE(4)
USER_LIST_R:			  10		USER_NUM(2)			[PLAYER_PACKETS/CON_PACKETS]
[PLAYER_PACKET]				  [		LEN_NAME(1)			NAME(V)					LEVEL(4)			XP(8)				PASSED(4)	]
[CON_PACKET]				  [		LEN_NAME(1)			NAME(V)					LEVEL(4)			WORD_CON(4)	   ]
SORT:					  11		USER_TYPE(1)		SORT_TYPE(1)(NAME / LV / WORD / XP / PASSED)
FILTER_NAME:			  12		USER_TYPE(1)		LEN_NAME(1)				NAME_VALUE(V)	
FILTER_OTHER:			  13		USER_TYPE(1)		FILTER_TYPE(LV / WORD / XP / PASSED)					FILTER_VALUE(4 / 8)
SF_R:					  14		USER_NUM(2)			[PLAYER_PACKETS/CON_PACKETS]
SF_PAGE:				  15		USER_TYPE(1)		USER_PER_PAGE(2)		PAGE(4)
GET_WORDS:				  16		PASSED(4)
GET_WORDS_R:			  17		TIME(2)				ROUND(1)				[LEN_WORD			WORD]
INC_XP:					  18		UID(4)				XP(8)
WORD_CON:				  19		UID(4)				LEN_WORD(1)				WORD(V)	
LOG_OUT:				  20		UID(4)
*/
